### ISSUE TITLE
`\p{…}` and `\P{…}` spec text

### ISSUE THREAD

**Issue by kdex** [mathiasbynens/es-regexp-unicode-character-class-escapes#4]
The simplest form of extending the current (ES 2015) syntax would probably be extending RegularExpressionBackslashSequence  with an optional Unicode property block. I've highlighted my diffs extending section [11.8.5 (Regular Expression Literals)](http://www.ecma-international.org/ecma-262/6.0/#sec-literals-regular-expression-literals).

<pre>
RegularExpressionLiteral ::
    / RegularExpressionBody / RegularExpressionFlags
RegularExpressionBody ::
    RegularExpressionFirstChar RegularExpressionChars
RegularExpressionChars ::
    [empty]
    RegularExpressionChars RegularExpressionChar
RegularExpressionFirstChar ::
    RegularExpressionNonTerminator but not one of * or \ or / or [
    RegularExpressionBackslashSequence
    RegularExpressionClass
RegularExpressionChar ::
    RegularExpressionNonTerminator but not one of \ or / or [
    RegularExpressionBackslashSequence
    RegularExpressionClass
RegularExpressionBackslashSequence ::
    \ RegularExpressionNonTerminator <b>RegularExpressionNonTerminatorBlock<sub>opt</sub></b>
<b>RegularExpressionNonTerminatorBlock ::</b>
    <b>RegularExpressionNonTerminatorBlockChar</b>
    <b>{ RegularExpressionNonTerminatorBlockChars }</b>
<b>RegularExpressionNonTerminatorBlockChars ::</b>
    <b>[empty]</b>
    <b>RegularExpressionNonTerminatorBlockChars RegularExpressionNonTerminatorBlockChar</b>
<b>RegularExpressionNonTerminatorBlockChar ::</b>
    <b>RegularExpressionNonTerminator but not }</b>
RegularExpressionNonTerminator ::
    SourceCharacter but not LineTerminator
RegularExpressionClass ::
    [ RegularExpressionClassChars ]
RegularExpressionClassChars ::
    [empty]
    RegularExpressionClassChars RegularExpressionClassChar
RegularExpressionClassChar ::
    RegularExpressionNonTerminator but not one of ] or \
    RegularExpressionBackslashSequence
RegularExpressionFlags ::
    [empty]
    RegularExpressionFlags IdentifierPart
</pre>

This would make `\p{…}`, `\P{…}` and others part of the syntax, but note that this approach would make `\d{…}` syntactically valid, too.

I'm not sure if empty _RegularExpressionNonTerminatorBlock_s should make any sense at all. It would be an easy fix for the grammar to enforce at least one character in _RegularExpressionNonTerminatorBlock_s, but I have yet to find out if any RE engine supports empty blocks and how they behave if they see them.

**Comment by kdex** [comment]
Addendum: `\d{…}` being parsed as a *RegularExpressionNonTerminatorBlock* is too risky, as this changes the behavior of [Quantifiers](http://www.ecma-international.org/ecma-262/6.0/#sec-patterns).

Example: In `\d{3}`, `{3}` should be parsed as a *Quantifier*, not as a *RegularExpressionNonTerminatorBlock*; but in `\p{Latin}`, the `{Latin}` part must be parsed as a *RegularExpressionNonTerminatorBlock*.

Maybe extending *RegularExpressionBackslashSequence* is not a good idea?

**Comment by kdex** [comment]
One more addendum: Most patterns are defined in [21.2.1 Patterns](http://www.ecma-international.org/ecma-262/6.0/#sec-patterns) anyway; so the extensions should *really* go there.

Anyway, I've noticed that [11.8.5 (Regular Expression Literals)](http://www.ecma-international.org/ecma-262/6.0/#sec-literals-regular-expression-literals) treats RegExp character classes as syntactically different (see *RegularExpressionClass*). Is there any reason to do that, and if so, do we need special care for Unicode property blocks?

**Comment by claudepache** [comment]
Note that the syntax in [11.8.5 (Regular Expression Literals](http://tc39.github.io/ecma262/#sec-literals-regular-expression-literals) is just used for recognisinig  the end of a regular expression literals `/.../` in ES code, and not for analysing it. At first glance, it should not be changed, because `\p` and `\P` are properly handled, and `{` and `}` do not play special role in that grammar.

The grammar that should be augmented is the one of [21.2.1 Patterns](http://tc39.github.io/ecma262/#sec-patterns), so that `\pX` and `\p{...}` are recognised as _Atom_. A first sketch:

<pre>
Atom[U] ::
    \  AtomEscape[?U]
    etc.

AtomEscape[U] ::
    DecimalEscape             <--- this is for \123
    CharacterEscape[?U]       <--- this is for \n, \uXXXX, etc. (a designated character)
    CharacterClassEscape<b>[?U]</b>  <--- this is for \d, \s, etc. (a class of characters)

CharacterClassEscape<b>[U]</b> ::
    d 
    D
    s 
    S 
    w 
    W
<b>    [+U] p <i>someLetter</i>
    [+U] p { <i> someSequence </i> }
    [+U] P <i> someLetter </i>
    [+U] P { <i> someSequence </i> }
</b>
</pre>

where _someLetter_ and _someSequence_ remain to be determined.

**Comment by mathiasbynens** [comment]
FWIW, ES4 did it very similarly: http://wiki.ecmascript.org/lib/exe/fetch.php?id=spec%3Aspec&cache=cache&media=spec:library-d2.html#RegExp%20grammar

```
CharacterClassEscape ::
    d                           => charset_digit
    D                           => CharsetComplement( charset_digit )
    s                           => charset_space
    S                           => CharsetComplement( charset_space )
    w                           => charset_word
    W                           => CharsetComplement( charset_word )
    p { UnicodeClass }          => unicodeClass( UnicodeClass )
    P { UnicodeClass }          => CharsetComplement( unicodeClass( UnicodeClass ) )
```

**Comment by mathiasbynens** [comment]
First draft: https://github.com/tc39/ecma262/compare/master...mathiasbynens:unicodePropertyEscape?expand=1 Feedback welcome!

**Comment by mathiasbynens** [comment]
Made it into a PR so it’s easier to leave comments on specific lines: https://github.com/mathiasbynens/ecma262/pull/1/files

**Comment by mathiasbynens** [comment]
cc @goyakim

**Comment by mathiasbynens** [comment]
https://github.com/tc39/proposal-regexp-unicode-property-escapes
